# Generated by Django 4.0 on 2021-12-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extenduser',
            old_name='username',
            new_name='user',
        ),
    ]
